app/Http/routes.php
<?php
/**
 * Main router file
 * 
 * Basic route definition
 * 
 * @category Router
 * @subpackage General
 * @package Olapus
 * @author Jan Drda <jdrda@outlook.com>
 * @copyright Jan Drda
 * @license https://opensource.org/licenses/MIT MIT
 */

/**
 * Root
 */
Route::get('/', ['as' => 'root', function () {
        return view('welcome');
}]);

/**
 * Main index
 */
Route::get('/home', function () {

    return redirect()->route('admin.dashboard.index');
});

/**
 * Admin
 */
Route::group(['prefix' => env('APP_ADMIN_URL', 'admin'), 'as' => 'admin.', 'middleware' => ['web', 'auth']], function () {


    /**
     * Main dashboard
     */
    Route::get('/', [
        'as' => 'dashboard.index', 'uses' => 'Admin\DashboardController@index'
    ]);
    
    /**
     * Articles and categories
     */
    Route::resource('page', 'Admin\PageController', ['names' => [
        'index' => 'page.index',
        'create' => 'page.create',
        'store' => 'page.store',
        'show' => 'page.show',
        'edit' => 'page.edit',
        'update' => 'page.update',
        'destroy' => 'page.destroy'
        ]]);
    Route::resource('pageCategory', 'Admin\PageCategoryController', ['names' => [
        'index' => 'pageCategory.index',
        'create' => 'pageCategory.create',
        'store' => 'pageCategory.store',
        'show' => 'pageCategory.show',
        'edit' => 'pageCategory.edit',
        'update' => 'pageCategory.update',
        'destroy' => 'pageCategory.destroy'
        ]]);
    
    /**
     * Articles and categories
     */
    Route::resource('article', 'Admin\ArticleController', ['names' => [
        'index' => 'article.index',
        'create' => 'article.create',
        'store' => 'article.store',
        'show' => 'article.show',
        'edit' => 'article.edit',
        'update' => 'article.update',
        'destroy' => 'article.destroy'
        ]]);
    Route::resource('articleCategory', 'Admin\ArticleCategoryController', ['names' => [
        'index' => 'articleCategory.index',
        'create' => 'articleCategory.create',
        'store' => 'articleCategory.store',
        'show' => 'articleCategory.show',
        'edit' => 'articleCategory.edit',
        'update' => 'articleCategory.update',
        'destroy' => 'articleCategory.destroy'
        ]]);
    
    /**
     * Feedback
     */
    Route::resource('feedback', 'Admin\FeedbackController', ['names' => [
        'index' => 'feedback.index',
        'create' => 'feedback.create',
        'store' => 'feedback.store',
        'show' => 'feedback.show',
        'edit' => 'feedback.edit',
        'update' => 'feedback.update',
        'destroy' => 'feedback.destroy'
        ]]);
    
    /**
     * Comment
     */
    Route::resource('comment', 'Admin\CommentController', ['names' => [
        'index' => 'comment.index',
        'create' => 'comment.create',
        'store' => 'comment.store',
        'show' => 'comment.show',
        'edit' => 'comment.edit',
        'update' => 'comment.update',
        'destroy' => 'comment.destroy'
        ]]);
    Route::get('comment/{id}/approve', [
        'as' => 'comment.approve', 'uses' => 'Admin\CommentController@approve'
    ]);
    Route::get('comment/{id}/spam', [
        'as' => 'comment.spam', 'uses' => 'Admin\CommentController@spam'
    ]);
    
    /**
     * Sliders and slides
     */
    Route::resource('slider', 'Admin\SliderController', ['names' => [
        'index' => 'slider.index',
        'create' => 'slider.create',
        'store' => 'slider.store',
        'show' => 'slider.show',
        'edit' => 'slider.edit',
        'update' => 'slider.update',
        'destroy' => 'slider.destroy'
        ]]);
    Route::resource('slide', 'Admin\SlideController', ['names' => [
        'index' => 'slide.index',
        'create' => 'slide.create',
        'store' => 'slide.store',
        'show' => 'slide.show',
        'edit' => 'slide.edit',
        'update' => 'slide.update',
        'destroy' => 'slide.destroy'
        ]]);
    
    /**
     * Images and categories
     */
    Route::resource('image', 'Admin\ImageController', ['names' => [
        'index' => 'image.index',
        'create' => 'image.create',
        'store' => 'image.store',
        'show' => 'image.show',
        'edit' => 'image.edit',
        'update' => 'image.update',
        'destroy' => 'image.destroy'
        ]]);
    Route::resource('imageCategory', 'Admin\ImageCategoryController', ['names' => [
        'index' => 'imageCategory.index',
        'create' => 'imageCategory.create',
        'store' => 'imageCategory.store',
        'show' => 'imageCategory.show',
        'edit' => 'imageCategory.edit',
        'update' => 'imageCategory.update',
        'destroy' => 'imageCategory.destroy'
        ]]);
    
     /**
     * Advertising
     */
    Route::resource('advert', 'Admin\AdvertController', ['names' => [
        'index' => 'advert.index',
        'create' => 'advert.create',
        'store' => 'advert.store',
        'show' => 'advert.show',
        'edit' => 'advert.edit',
        'update' => 'advert.update',
        'destroy' => 'advert.destroy'
        ]]);
    Route::resource('advertLocation', 'Admin\AdvertLocationController', ['names' => [
        'index' => 'advertLocation.index',
        'create' => 'advertLocation.create',
        'store' => 'advertLocation.store',
        'show' => 'advertLocation.show',
        'edit' => 'advertLocation.edit',
        'update' => 'advertLocation.update',
        'destroy' => 'advertLocation.destroy'
        ]]);
    
    /**
     * Products and categories
     */
    Route::resource('productCategory', 'Admin\ProductCategoryController', ['names' => [
        'index' => 'productCategory.index',
        'create' => 'productCategory.create',
        'store' => 'productCategory.store',
        'show' => 'productCategory.show',
        'edit' => 'productCategory.edit',
        'update' => 'productCategory.update',
        'destroy' => 'productCategory.destroy'
        ]]);
    Route::resource('product', 'Admin\ProductController', ['names' => [
        'index' => 'product.index',
        'create' => 'product.create',
        'store' => 'product.store',
        'show' => 'product.show',
        'edit' => 'product.edit',
        'update' => 'product.update',
        'destroy' => 'product.destroy'
        ]]);
    
    /**
     * Settings
     */
    Route::resource('settings', 'Admin\SettingsController', [
        'except' => ['delete', 'show'],
        'names' => [
        'index' => 'settings.index',
        'create' => 'settings.create',
        'store' => 'settings.store',
        'show' => 'settings.show',
        'edit' => 'settings.edit',
        'update' => 'settings.update',
        'destroy' => 'settings.destroy'
        ]]);
    
    /**
     * Users
     */
    Route::resource('user', 'Admin\UserController', [
        'except' => ['show'],
        'names' => [
        'index' => 'user.index',
        'create' => 'user.create',
        'store' => 'user.store',
        'show' => 'user.show',
        'edit' => 'user.edit',
        'update' => 'user.update',
        'destroy' => 'user.destroy'
        ]]);
    
});

/**
 * Authentication
 */
Route::group(['middleware' => 'web'], function () {

    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login')->name('authPostLogin');
    Route::any('logout', 'Auth\LoginController@logout')->name('logout');

    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('authPasswordEmailGet');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');

    // Registration Routes...
    //Route::get('register', 'Auth\RegisterController@showRegistrationForm');
    //Route::post('register', 'Auth\RegisterController@register');

});

/**
 * Images
 */
Route::get('{imagePath}', [
    'as' => 'getImage', 'uses' => 'Media\ImageController@getImage'
]);


/**
 * Custom routes
 */
require_once('routesCustom.php');

app/Image.php
<?php
/**
 * Image module model
 * 
 * Model for module Image
 * 
 * @category Model
 * @subpackage Admin
 * @package Olapus
 * @author Jan Drda <jdrda@outlook.com>
 * @copyright Jan Drda
 * @license https://opensource.org/licenses/MIT MIT
 */
namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Image extends Model
{
    use SoftDeletes, AdminModelTrait;
    
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'image';
    
    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime',
    ];



    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'description', 'alt', 'url'];
    
    /**
     * Columns to exclude from index
     * 
     * @var array 
     */
    protected $excludedFromIndex = [];
    
    /**
     * Hidden from custom find
     * 
     * @var arrat 
     */
    protected  $excludedFromFind = [];
    
    /**
     * Fields to search in fulltext mode
     * 
     * @var array
     */
    protected $fulltextFields = [
        'id',
        'name' => [
            'operator' => 'LIKE',
            'prefix' => '%',
            'sufix' => '%'
        ],
        'description' => [
            'operator' => 'LIKE',
            'prefix' => '%',
            'sufix' => '%'
        ],
        'alt' => [
            'operator' => 'LIKE',
            'prefix' => '%',
            'sufix' => '%'
        ],
        'url' => [
            'operator' => 'LIKE',
            'prefix' => '%',
            'sufix' => '%'
        ],
    ];
    
    /**
     * Default order by
     * 
     * @type array
     */
    protected $defaultOrderBy = [
      'id' => 'desc'  
    ];
    
    /**
     * Image category link
     * 
     * @return object
     */
    public function imagecategories(){
        
        return $this->belongsTo('App\ImageCategory', 'imagecategory_id');
    }
    
    /**
     * Slide link
     * 
     * @return object
     */
    public function slides(){
        
        return $this->hasMany('App\Slide', 'image_id');
    }
    
    /**
     * Article category
     * 
     * @return object
     */
    public function articlecategories(){
        
        return $this->hasMany('App\ArticleCategory', 'image_id');
    }
    
    /**
     * Article category
     * 
     * @return object
     */
    public function pages(){
        
        return $this->hasMany('App\Page', 'image_id');
    }
    
    /**
     * Process relationships
     * 
     * @param query $query
     * @return query
     */
    public function scopeRelationships($query){
        
        return $query->with('imagecategories');
    }
    
    /**
     * Hide fields
     * 
     * @param array $array
     */
    public function hide($array = []){
        
        $this->hidden = ['image'];
    }
}

app/Http/Controllers/Admin/ImageController.php
<?php
/**
 * Image module controller
 * 
 * Controller for module Image
 * 
 * @category Controller
 * @subpackage Admin
 * @package Olapus
 * @author Jan Drda <jdrda@outlook.com>
 * @copyright Jan Drda
 * @license https://opensource.org/licenses/MIT MIT
 */

namespace App\Http\Controllers\Admin;

use App\Helpers;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class ImageController extends AdminModuleController
{
   
    /**
     * Constructor
     */
    public function __construct() {
        parent::__construct();

        $this->middleware('add.lookup.tables:ImageCategory', ['only' => ['index','create','edit']]);
    }
   
    /**
     * Validation rules
     */
    protected $arValidationArray = [
                    'name' => 'required|max:255',
                    'description' => 'max:255',
                    'alt' => 'max:255',
                    'url' => 'max:255|unique:image,url'
    ];
   
    /**
     * Binary fields
     * 
     * @var array 
     */
    protected $binaryFields = [];
            
    /**
     * Get number of pagination rows
     * 
     * @return integer
     */
    public function getRowsToPaginate(){
        
        return env('ADMIN_MEDIA_PAGINATE', 12);
    }
    
    /**
     * Associate relationships to other table
     * 
     * @param object $object
     * @param Request $request
     */
    public function associateRelationships($object, Request $request){
        
        /**
         * Validate category ID, if failed set to default
         */
        $validator = Validator::make($request->all(), [
            'imagecategory_id' => 'required|integer|min:1|exists:imagecategory,id',
        ]);
        
        /**
         * Validator fails - set category to default
         */
        if ($validator->fails()) {

            $object->imagecategories()->associate(1);
        }
        
        /**
         * Validator OK - save it
         */
        else{

            $object->imagecategories()->associate($request->input('imagecategory_id'));
        } 
    }

    /**
     * Save media to storage
     *
     * @param object $object
     * @param Request $request
     * @param boolean $update
     * @return boolean
     */
    public function saveMediaToStorage($object, $request, $update = FALSE) {

        /**
         * Check if requested and then save
         */
        if ($update == FALSE || ($update == TRUE && $request->has('image'))) {

            /**
             * Image has an url
             */
            if(strlen($request->input('url') > 5)){
                $object->addMedia($request->file('image'))->toMediaCollection('images')
                    ->usingName($request->input('url'));
            }
            else{
                $object->addMedia($request->file('image'))->toMediaCollection('images');
            }

            /**
             * Update meta information
             */
            return TRUE;
        }

        return FALSE;
    }

}

app/Http/Controllers/Media/ImageController.php
<?php
/**
 * Media controller
 * 
 * Basic controller for media functions
 * 
 * @category Controller
 * @subpackage Media
 * @package Olapus
 * @author Jan Drda <jdrda@outlook.com>
 * @copyright Jan Drda
 * @license https://opensource.org/licenses/MIT MIT
 */

namespace App\Http\Controllers\Media;

use App\Helpers;
use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use App\Image;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Storage;
use Carbon\Carbon;

class ImageController extends Controller
{
   
   /**
    * Get image from storage
    * 
    * @param Request $request
    * @return file
    */
    public function getImage(Request $request)
    {

        /**
         * Get META information
         */
        $imageMeta = Image::where(['url' => $request->imageName])->first();

        /**
         * File does not exist
         */
        if(empty($imageMeta) == TRUE){
            App::abort(404);
        }

        $mediaItems = $imageMeta->getMedia();
        $fullPathOnDisk = $mediaItems[0]->getPath();


        /**
         * Prepare stream
         */
        $stream = Storage::readStream($fullPathOnDisk);

      
        /**
         * File headers
         */
        $headers = array(
            'Content-Description'       => 'File Transfer',
            'Content-Transfer-Encoding' => 'binary',
            'Pragma'                    => 'public',
            'Expires'                   => Carbon::createFromTimestamp(time()+3600)->toRfc2822String(),
            'Last-Modified'             => $imageMeta->updated_at->toRfc2822String()
        );
        
        /**
         * Response code cached
         */
        if( (isset($_SERVER['HTTP_IF_NONE_MATCH']) && $_SERVER['HTTP_IF_NONE_MATCH'] == $imageMeta->image_etag)
                || (isset($_SERVER['HTTP_IF_MODIFIED_SINCE']) && $_SERVER['HTTP_IF_MODIFIED_SINCE'] == $imageMeta->updated_at->toRfc2822String()) ){
            
            $responseCode = 304;
        }
        
        /**
         * Response code not cached, but OK
         */
        else{
            
            $responseCode = 200;
        }

        /**
         * Stream to browser
         */
        return Response::stream(function() use ($stream) {
                    fpassthru($stream);
                }, $responseCode, $headers);
    }
}

resources/views/admin/modules/image/index.blade.php
@extends('admin.master')

@section('page-name', trans('admin_module_image.name') )

@section('page-icon', 'fa fa-image')

@section('page-description', trans('admin_module_image.description'))

@section('delete_confirmation_text', trans('admin_module_image.delete_row_confirmation'))

@section('menu-class-media', 'active')
@section('menu-class-image', 'active')

@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">
                    {{ trans($moduleNameBlade . '.name') }}
                    <small>({{ trans('admin.total_rows') }} {{ $results->count() }} {{ trans('admin.of') }} {{ $results->total() }}, {{ trans('admin.showing_page') }} {{ $results->currentPage() }} {{ trans('admin.of') }} {{ $results->lastPage() }})</small>
                </h3>


                <div class="box-tools">

                    <form action="{{ route('admin.image.index') }}" method="get">

                        <!-- Search box -->
                        <div class="input-group input-group-sm" style="width: 200px;">
                            <input type="text" name="search" class="form-control pull-right" placeholder="{{ trans('admin.search') }}" value="{{ request('search') }}">

                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                            <!-- /Search box -->

                            <a href="{{ route('admin.image.create') }}" class="btn btn-success btn-sm form-control">
                                <i class="fa fa-plus"></i> {{ trans('admin.add_new') }}
                            </a>
                        </div>

                    </form>

                </div>

            </div>
            <!-- /.box-header -->

            <!-- Data table -->
            <div class="box-body">
                
                <div class='row'>
                    <div class='col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4'>
                    @include('admin.errors')
                    </div>
                </div>
                <table class="table table-hover table-responsive">
                    <tbody>
                        <tr>
                            <th>
                                <a href="@if(Request::has('orderbycolumn') and request('orderbycolumn') == 'id' and request('orderbytype') == 'asc'){{ route($moduleBasicRoute . '.index', ['search' => request('search'), 'orderbycolumn' => 'id', 'orderbytype' => 'desc']) }}@else{{ route($moduleBasicRoute . '.index', ['search' => request('search'), 'orderbycolumn' => 'id', 'orderbytype' => 'asc']) }}@endif">
                                    {{ trans($moduleNameBlade . '.fields.id') }}
                                    @if(Request::has('orderbycolumn'))
                                        @if(request('orderbycolumn') == 'id')
                                        <i class='fa fa-sort-numeric-{{ request('orderbytype') == 'asc' ? 'asc' : 'desc' }}'></i>
                                        @endif
                                    @else
                                    <i class='fa fa-sort-numeric-desc'></i>
                                    @endif
                                </a>
                            </th>
                            <th>
                                <a href="@if(Request::has('orderbycolumn') and request('orderbycolumn') == 'name' and request('orderbytype') == 'asc'){{ route($moduleBasicRoute . '.index', ['search' => request('search'), 'orderbycolumn' => 'name', 'orderbytype' => 'desc']) }}@else{{ route($moduleBasicRoute . '.index', ['search' => request('search'), 'orderbycolumn' => 'name', 'orderbytype' => 'asc']) }}@endif">
                                    {{ trans($moduleNameBlade . '.fields.name') }}
                                    @if(Request::has('orderbycolumn') and request('orderbycolumn') == 'name')
                                    <i class='fa fa-sort-alpha-{{ request('orderbytype') == 'asc' ? 'asc' : 'desc' }}'></i>
                                    @endif
                                </a>
                            </th>
                            <th class="hidden-xs">
                                <form action="{{ route($moduleBasicRoute . '.index') }}" method="get" id='imageCategoryForm'>
                                    <select name='relation' id='imagecategory_id' class='input-sm'>
                                        <option value=''>{{ trans($moduleNameBlade . '.fields.category') }} ...</option>
                                        @foreach (request('ImageCategory') as $imageCategory)
                                        <option value='imageCategory:{{ $imageCategory->id }}' @if(request('external_tables_filter')['imageCategory'] == $imageCategory->id) selected @endif>{{ $imageCategory->name }}</option>
                                        @endforeach
                                    </select>
                                </form>
                                
                            </th>
                            <th class="hidden-xs hidden-sm">
                                <a href="@if(Request::has('orderbycolumn') and request('orderbycolumn') == 'updated_at' and request('orderbytype') == 'asc'){{ route('admin.user.index', ['search' => request('search'), 'orderbycolumn' => 'updated_at', 'orderbytype' => 'desc']) }}@else{{ route($moduleBasicRoute . '.index', ['search' => request('search'), 'orderbycolumn' => 'updated_at', 'orderbytype' => 'asc']) }}@endif">
                                    {{ trans($moduleNameBlade . '.fields.updated_at') }}
                                    @if(Request::has('orderbycolumn') and request('orderbycolumn') == 'updated_at')
                                    <i class='fa fa-sort-numeric-{{ request('orderbytype') == 'asc' ? 'asc' : 'desc' }}'></i>
                                    @endif
                                </a>
                            </th>
                        </tr>
                    </tbody>
                </table>
                <div class='row'>
                    &nbsp;
                </div>


                <div class="row">
                    @foreach ($results as $result)            
                    <div class="col-xs-6 col-sm-3 col-md-2">
                        <div class="panel panel-{{ $result->imagecategories()->first()->color }}">
                            <div class="panel-heading" style="white-space: nowrap; overflow: hidden; text-overflow: ellipsis" data-toggle="tooltip" data-placement="top" title="{{ $result->name }}">{{ $result->name }}</div>
                            <div class="panel-body image-square row-xs-flex-center text-center">
                                <a href="#" data-toggle="modal" data-target="#imageDetailModal{{ $result->id }}">
                                    <img data-original="{{ route('getImage', ['imageName' => $result->url, 'imageExtension' => $result->image_extension]) }}" alt="{{ $result->name }}" class="img-responsive lazy" style="margin: 0 auto; float: none;"  data-toggle="tooltip" data-placement="bottom" title="{{ $result->imagecategories->name }}">
                                </a>  
                            </div>
                            <div class="panel-footer text-center">
                                <div class="btn-group">
                                    
                                    <button type="button" class="btn btn-primary dropdown-toggle btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        {{ trans('admin_module_image.action') }} <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu">
                                        <li><a href="#" data-toggle="modal" data-target="#imageURLModal{{ $result->id }}"><i class="fa fa-link"></i> {{ trans('admin_module_image.get_url') }}</a></li>
                                        <li><a href="#" data-toggle="modal" data-target="#imageDetailModal{{ $result->id }}"><i class="fa fa-info-circle"></i> {{ trans('admin_module_image.get_info') }}</a></li>
                                        <li role="separator" class="divider"></li>
                                        <li><a href="{{ route($moduleBasicRoute . '.edit', $result->id) }}"><i class="fa fa-pencil"></i> {{ trans('admin.edit') }}</a></li>
                                        <li><a href="#" data-toggle="modal" data-target="#deleteModal{{ $result->id }}"><i class="fa fa-remove"></i> {{ trans('admin.delete') }}</a></li>
                                    </ul>
                                </div>                  
                            </div>
                        </div>
                    </div>
                    @endforeach
                </div>


                
                <hr>
                <div class="row">
                    <div class="col-xs-12 text-center"> 
                        {!! $results->render() !!}
                    </div>
                </div>
            </div>
            <!-- Data table -->
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>
@endsection

@section('foot')

@include('admin/modules/image_detail_modals');
@include('admin/modules/image_url_modals');
@include('admin/modules/delete_modals');

@parent

<script>

$( document ).ready(function() {
    
    // image containers must be squares
    squareThis('.image-square');
    
    $(".image-square img").css({ "max-height": $(".image-square").height() + 'px' });

    // lazyload images
    $("img.lazy").lazyload({
        effect : "fadeIn"
    });

    $('.url_modal').on('shown.bs.modal', function () {
        $(this).add('input').select();
    });
    
    // Category filter
    $('#imagecategory_id').on('change', function() {
        $('#imageCategoryForm').submit();
    });
});
</script>

@endsection