app/Http/routes.php
<?php
/**
 * Main router file
 * 
 * Basic route definition
 * 
 * @category Router
 * @subpackage General
 * @package Olapus
 * @author Jan Drda <jdrda@outlook.com>
 * @copyright Jan Drda
 * @license https://opensource.org/licenses/MIT MIT
 */

/**
 * Root
 */
Route::get('/', ['as' => 'root', function () {
        return view('welcome');
}]);

/**
 * Main index
 */
Route::get('/home', function () {

    return redirect()->route('admin.dashboard.index');
});

/**
 * Admin
 */
Route::group(['prefix' => env('APP_ADMIN_URL', 'admin'), 'as' => 'admin.', 'middleware' => ['web', 'auth']], function () {


    /**
     * Main dashboard
     */
    Route::get('/', [
        'as' => 'dashboard.index', 'uses' => 'Admin\DashboardController@index'
    ]);
    
    /**
     * Articles and categories
     */
    Route::resource('page', 'Admin\PageController', ['names' => [
        'index' => 'page.index',
        'create' => 'page.create',
        'store' => 'page.store',
        'show' => 'page.show',
        'edit' => 'page.edit',
        'update' => 'page.update',
        'destroy' => 'page.destroy'
        ]]);
    Route::resource('pageCategory', 'Admin\PageCategoryController', ['names' => [
        'index' => 'pageCategory.index',
        'create' => 'pageCategory.create',
        'store' => 'pageCategory.store',
        'show' => 'pageCategory.show',
        'edit' => 'pageCategory.edit',
        'update' => 'pageCategory.update',
        'destroy' => 'pageCategory.destroy'
        ]]);
    
    /**
     * Articles and categories
     */
    Route::resource('article', 'Admin\ArticleController', ['names' => [
        'index' => 'article.index',
        'create' => 'article.create',
        'store' => 'article.store',
        'show' => 'article.show',
        'edit' => 'article.edit',
        'update' => 'article.update',
        'destroy' => 'article.destroy'
        ]]);
    Route::resource('articleCategory', 'Admin\ArticleCategoryController', ['names' => [
        'index' => 'articleCategory.index',
        'create' => 'articleCategory.create',
        'store' => 'articleCategory.store',
        'show' => 'articleCategory.show',
        'edit' => 'articleCategory.edit',
        'update' => 'articleCategory.update',
        'destroy' => 'articleCategory.destroy'
        ]]);
    
    /**
     * Feedback
     */
    Route::resource('feedback', 'Admin\FeedbackController', ['names' => [
        'index' => 'feedback.index',
        'create' => 'feedback.create',
        'store' => 'feedback.store',
        'show' => 'feedback.show',
        'edit' => 'feedback.edit',
        'update' => 'feedback.update',
        'destroy' => 'feedback.destroy'
        ]]);
    
    /**
     * Comment
     */
    Route::resource('comment', 'Admin\CommentController', ['names' => [
        'index' => 'comment.index',
        'create' => 'comment.create',
        'store' => 'comment.store',
        'show' => 'comment.show',
        'edit' => 'comment.edit',
        'update' => 'comment.update',
        'destroy' => 'comment.destroy'
        ]]);
    Route::get('comment/{id}/approve', [
        'as' => 'comment.approve', 'uses' => 'Admin\CommentController@approve'
    ]);
    Route::get('comment/{id}/spam', [
        'as' => 'comment.spam', 'uses' => 'Admin\CommentController@spam'
    ]);
    
    /**
     * Sliders and slides
     */
    Route::resource('slider', 'Admin\SliderController', ['names' => [
        'index' => 'slider.index',
        'create' => 'slider.create',
        'store' => 'slider.store',
        'show' => 'slider.show',
        'edit' => 'slider.edit',
        'update' => 'slider.update',
        'destroy' => 'slider.destroy'
        ]]);
    Route::resource('slide', 'Admin\SlideController', ['names' => [
        'index' => 'slide.index',
        'create' => 'slide.create',
        'store' => 'slide.store',
        'show' => 'slide.show',
        'edit' => 'slide.edit',
        'update' => 'slide.update',
        'destroy' => 'slide.destroy'
        ]]);
    
    /**
     * Images and categories
     */
    Route::resource('image', 'Admin\ImageController', ['names' => [
        'index' => 'image.index',
        'create' => 'image.create',
        'store' => 'image.store',
        'show' => 'image.show',
        'edit' => 'image.edit',
        'update' => 'image.update',
        'destroy' => 'image.destroy'
        ]]);
    Route::resource('imageCategory', 'Admin\ImageCategoryController', ['names' => [
        'index' => 'imageCategory.index',
        'create' => 'imageCategory.create',
        'store' => 'imageCategory.store',
        'show' => 'imageCategory.show',
        'edit' => 'imageCategory.edit',
        'update' => 'imageCategory.update',
        'destroy' => 'imageCategory.destroy'
        ]]);
    
     /**
     * Advertising
     */
    Route::resource('advert', 'Admin\AdvertController', ['names' => [
        'index' => 'advert.index',
        'create' => 'advert.create',
        'store' => 'advert.store',
        'show' => 'advert.show',
        'edit' => 'advert.edit',
        'update' => 'advert.update',
        'destroy' => 'advert.destroy'
        ]]);
    Route::resource('advertLocation', 'Admin\AdvertLocationController', ['names' => [
        'index' => 'advertLocation.index',
        'create' => 'advertLocation.create',
        'store' => 'advertLocation.store',
        'show' => 'advertLocation.show',
        'edit' => 'advertLocation.edit',
        'update' => 'advertLocation.update',
        'destroy' => 'advertLocation.destroy'
        ]]);
    
    /**
     * Products and categories
     */
    Route::resource('productCategory', 'Admin\ProductCategoryController', ['names' => [
        'index' => 'productCategory.index',
        'create' => 'productCategory.create',
        'store' => 'productCategory.store',
        'show' => 'productCategory.show',
        'edit' => 'productCategory.edit',
        'update' => 'productCategory.update',
        'destroy' => 'productCategory.destroy'
        ]]);
    Route::resource('product', 'Admin\ProductController', ['names' => [
        'index' => 'product.index',
        'create' => 'product.create',
        'store' => 'product.store',
        'show' => 'product.show',
        'edit' => 'product.edit',
        'update' => 'product.update',
        'destroy' => 'product.destroy'
        ]]);
    
    /**
     * Settings
     */
    Route::resource('settings', 'Admin\SettingsController', [
        'except' => ['delete', 'show'],
        'names' => [
        'index' => 'settings.index',
        'create' => 'settings.create',
        'store' => 'settings.store',
        'show' => 'settings.show',
        'edit' => 'settings.edit',
        'update' => 'settings.update',
        'destroy' => 'settings.destroy'
        ]]);
    
    /**
     * Users
     */
    Route::resource('user', 'Admin\UserController', [
        'except' => ['show'],
        'names' => [
        'index' => 'user.index',
        'create' => 'user.create',
        'store' => 'user.store',
        'show' => 'user.show',
        'edit' => 'user.edit',
        'update' => 'user.update',
        'destroy' => 'user.destroy'
        ]]);
    
});

/**
 * Authentication
 */
Route::group(['middleware' => 'web'], function () {

    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login')->name('authPostLogin');
    Route::any('logout', 'Auth\LoginController@logout')->name('logout');

    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('authPasswordEmailGet');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');

    // Registration Routes...
    //Route::get('register', 'Auth\RegisterController@showRegistrationForm');
    //Route::post('register', 'Auth\RegisterController@register');

});

/**
 * Images
 */
Route::get('{imagePath}', [
    'as' => 'getImage', 'uses' => 'Media\ImageController@getImage'
]);


/**
 * Custom routes
 */
require_once('routesCustom.php');

app/Slider.php
<?php
/**
 * Sllider module model
 * 
 * Model for module Slider
 * 
 * @category Model
 * @subpackage Admin
 * @package Olapus
 * @author Jan Drda <jdrda@outlook.com>
 * @copyright Jan Drda
 * @license https://opensource.org/licenses/MIT MIT
 */

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Slider extends Model
{
    use SoftDeletes, AdminModelTrait;
    
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'slider';
    
    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $casts = [
        'created_at' => 'datetime',
        'updated_at' => 'datetime',
        'deleted_at' => 'datetime',
    ];
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'description', 'cycle_interval'];
    
    /**
     * Columns to exclude from index
     * 
     * @var array 
     */
    protected $excludedFromIndex = [];
    
    /**
     * Fields to search in fulltext mode
     * 
     * @var array
     */
    protected $fulltextFields = [
        'id',
        'name' => [
            'operator' => 'LIKE',
            'prefix' => '%',
            'sufix' => '%'
        ],
        'description' => [
            'operator' => 'LIKE',
            'prefix' => '%',
            'sufix' => '%'
        ],
        'cycle_interval',
    ];
    
    /**
     * Default order by
     * 
     * @var array
     */
    protected $defaultOrderBy = [
      'id' => 'desc'  
    ];
    
    /**
     * Slide link
     * 
     * @return object
     */
    public function slides(){
        
        return $this->hasMany('App\Slide', 'slider_id')->orderBy('position', 'asc');
    }
    
    /**
     * Process relationships
     * 
     * @param query $query
     * @return query
     */
    public function scopeRelationships($query){
        
        return $query->with('slides', 'slides.images', 'slides.images', 'slides.images.imagecategories');
    }
}

app/Http/Controllers/Admin/SliderController.php
<?php
/**
 * Slider module controller
 * 
 * Controller for module Slider
 * 
 * @category Controller
 * @subpackage Admin
 * @package Olapus
 * @author Jan Drda <jdrda@outlook.com>
 * @copyright Jan Drda
 * @license https://opensource.org/licenses/MIT MIT
 */

namespace App\Http\Controllers\Admin;

class SliderController extends AdminModuleController
{
    /**
     * Validation rules
     * 
     * @var array
     */
    protected $arValidationArray = [
                    'name' => 'required|max:255|unique:slider,name',
                    'description' => 'max:255',
                    'cycle_interval' => 'required|integer|min:1'];
}

resources/views/admin/modules/slider/create_edit.blade.php
@extends('admin.master')

@section('page-name', trans($moduleNameBlade . '.name') )

@section('page-icon', 'fa fa-sideshare')

@section('page-description', trans($moduleNameBlade . '.description'))

@section('menu-class-components', 'active')
@section('menu-class-slider', 'active')

@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">
                    {{ trans($moduleNameBlade . '.name') }}
                </h3>


                <div class="box-tools">


                    <!-- Search box DEACTIVATED -->
                    <!--<div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                        </div>
                    </div>-->
                    <!-- /Search box DEACTIVATED -->
                </div>

            </div>
            <!-- /.box-header -->
            
            <div class='box-body'>
                <div class='row'>
                    <div class='col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4'>

                        @include('admin.errors')

                        <!-- Form -->
                        <form action="@if(isset($results->_method)){{ route($moduleBasicRoute . '.update', $results->id) }}@else{{ route($moduleBasicRoute . '.store') }}@endif" method="post">
                            {!! csrf_field() !!}
                            @if(isset($results->_method))
                            <input type="hidden" name="_method" value="{{ $results->_method }}">
                            @endif
                            <div class="form-group has-feedback">
                                <label for='name'>{{ trans($moduleNameBlade . '.fields.name') }} *</label>
                                <input type="text" name="name" class="form-control" value="{{ $results->name ?? old('name') }}" required>
                                <span class="fa fa-key form-control-feedback"></span>
                            </div>
                            <div class="form-group has-feedback">
                                <label for='description'>{{ trans($moduleNameBlade . '.fields.description') }}</label>
                                <input type="text" name="description" class="form-control" value="{{ $results->description ?? old('description') }}">
                                <span class="fa fa-align-left form-control-feedback"></span>
                            </div>
                            <div class="form-group has-feedback">
                                <label for='cycle_interval'>{{ trans($moduleNameBlade . '.fields.cycle_interval') }}</label>
                                <input type="number" min="1" name="cycle_interval" class="form-control" value="@if(isset($results->cycle_interval) ?? old('cycle_interval') != NULL){{ $results->cycle_interval ?? old('cycle_interval') }}@else{{ 5000 }}@endif">
                                <span class="fa fa-clock-o form-control-feedback"></span>
                            </div>
                            
                            <div class="form-group text-right">
                                @if(isset($results->_method))                               
                                <a href='{{ route('admin.slide.index', ['relation' => 'slider:' . $results->id ]) }}' name='show_slides' class='btn btn-warning btn-flat'>{{ trans('admin_module_slider.show_slides') }}</a>
                                @endif
                                <button type='submit' name='submit' class='btn btn-primary btn-flat'>{{ trans('admin.save') }}</button>
                            </div>
                        </form>
                        <!-- /Form -->
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>
@endsection

resources/views/admin/modules/slider/index.blade.php
@extends('admin.master')

@section('page-name', trans($moduleNameBlade . '.name') )

@section('page-icon', 'fa fa-slideshare')

@section('page-description', trans($moduleNameBlade . '.description'))

@section('delete_confirmation_text', trans($moduleNameBlade . '.delete_row_confirmation'))

@section('menu-class-components', 'active')
@section('menu-class-slider', 'active')

@section('content')
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">
                    {{ trans($moduleNameBlade . '.name') }}
                    <small>({{ trans('admin.total_rows') }} {{ $results->count() }} {{ trans('admin.of') }} {{ $results->total() }}, {{ trans('admin.showing_page') }} {{ $results->currentPage() }} {{ trans('admin.of') }} {{ $results->lastPage() }})</small>
                </h3>


                <div class="box-tools">

                    <form action="{{ route($moduleBasicRoute . '.index') }}" method="get">

                        <!-- Search box -->
                        <div class="input-group input-group-sm" style="width: 200px;">
                            <input type="text" name="search" class="form-control pull-right" placeholder="{{ trans('admin.search') }}" value="{{ request('search') }}">

                            <div class="input-group-btn">
                                <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                            </div>
                            <!-- /Search box -->

                            <a href="{{ route($moduleBasicRoute . '.create') }}" class="btn btn-success btn-sm form-control">
                                <i class="fa fa-plus"></i> {{ trans('admin.add_new') }}
                            </a>
                        </div>

                    </form>

                </div>

            </div>
            <!-- /.box-header -->

            <!-- Data table -->
            <div class="box-body no-padding">
                
                <div class='row'>
                    <div class='col-xs-12 col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4'>
                    @include('admin.errors')
                    </div>
                </div>
                <table class="table table-hover table-responsive">
                    <tbody>
                        <tr>
                           <th>
                                <a href="@if(Request::has('orderbycolumn') and request('orderbycolumn') == 'id' and request('orderbytype') == 'asc'){{ route($moduleBasicRoute . '.index', ['search' => request('search'), 'orderbycolumn' => 'id', 'orderbytype' => 'desc']) }}@else{{ route($moduleBasicRoute . '.index', ['search' => request('search'), 'orderbycolumn' => 'id', 'orderbytype' => 'asc']) }}@endif">
                                    {{ trans($moduleNameBlade . '.fields.id') }}
                                    @if(Request::has('orderbycolumn'))
                                        @if(request('orderbycolumn') == 'id')
                                        <i class='fa fa-sort-numeric-{{ request('orderbytype') == 'asc' ? 'asc' : 'desc' }}'></i>
                                        @endif
                                    @else
                                    <i class='fa fa-sort-numeric-desc'></i>
                                    @endif
                                </a>
                            </th>
                            <th>
                                <a href="@if(Request::has('orderbycolumn') and request('orderbycolumn') == 'name' and request('orderbytype') == 'asc'){{ route($moduleBasicRoute . '.index', ['search' => request('search'), 'orderbycolumn' => 'name', 'orderbytype' => 'desc']) }}@else{{ route($moduleBasicRoute . '.index', ['search' => request('search'), 'orderbycolumn' => 'name', 'orderbytype' => 'asc']) }}@endif">
                                    {{ trans($moduleNameBlade . '.fields.name') }}
                                    @if(Request::has('orderbycolumn') and request('orderbycolumn') == 'name')
                                    <i class='fa fa-sort-alpha-{{ request('orderbytype') == 'asc' ? 'asc' : 'desc' }}'></i>
                                    @endif
                                </a>
                            </th>
                            <th class="hidden-xs">
                                 <a href="@if(Request::has('orderbycolumn') and request('orderbycolumn') == 'description' and request('orderbytype') == 'asc'){{ route($moduleBasicRoute . '.index', ['search' => request('search'), 'orderbycolumn' => 'description', 'orderbytype' => 'desc']) }}@else{{ route($moduleBasicRoute . '.index', ['search' => request('search'), 'orderbycolumn' => 'description', 'orderbytype' => 'asc']) }}@endif">
                                    {{ trans($moduleNameBlade . '.fields.description') }}
                                    @if(Request::has('orderbycolumn') and request('orderbycolumn') == 'description')
                                    <i class='fa fa-sort-alpha-{{ request('orderbytype') == 'asc' ? 'asc' : 'desc' }}'></i>
                                    @endif
                                </a>
                                
                            </th>
                            <th class="hidden-xs hidden-sm">
                                 <a href="@if(Request::has('orderbycolumn') and request('orderbycolumn') == 'cycle_interval' and request('orderbytype') == 'asc'){{ route($moduleBasicRoute . '.index', ['search' => request('search'), 'orderbycolumn' => 'cycle_interval', 'orderbytype' => 'desc']) }}@else{{ route($moduleBasicRoute . '.index', ['search' => request('search'), 'orderbycolumn' => 'cycle_interval', 'orderbytype' => 'asc']) }}@endif">
                                    {{ trans($moduleNameBlade . '.fields.cycle_interval') }}
                                    @if(Request::has('orderbycolumn') and request('orderbycolumn') == 'cycle_interval')
                                    <i class='fa fa-sort-alpha-{{ request('orderbytype') == 'asc' ? 'asc' : 'desc' }}'></i>
                                    @endif
                                </a>
                                
                            </th>
                            <th class="hidden-xs hidden-sm">
                                 <a href="@if(Request::has('orderbycolumn') and request('orderbycolumn') == 'updated_at' and request('orderbytype') == 'asc'){{ route($moduleBasicRoute . '.index', ['search' => request('search'), 'orderbycolumn' => 'updated_at', 'orderbytype' => 'desc']) }}@else{{ route($moduleBasicRoute . '.index', ['search' => request('search'), 'orderbycolumn' => 'updated_at', 'orderbytype' => 'asc']) }}@endif">
                                    {{ trans($moduleNameBlade . '.fields.updated_at') }}
                                    @if(Request::has('orderbycolumn') and request('orderbycolumn') == 'updated_at')
                                    <i class='fa fa-sort-alpha-{{ request('orderbytype') == 'asc' ? 'asc' : 'desc' }}'></i>
                                    @endif
                                </a>
                                
                            </th>
                            <th class="text-right">
                                {{ trans('admin.actions') }}
                            </th>
                        </tr>
                        @foreach ($results as $result)
                        <tr>
                            <td>{{ $result->id }}</td>
                            <td>{{ $result->name }}</td>
                            <td class="hidden-xs">{{ $result->description }}</td>
                            <td class="hidden-xs hidden-sm">{{ $result->cycle_interval }}</td>
                            <td class="hidden-xs hidden-sm">{{ $result->updated_at->format(trans('locale.date_format')) }}</td>
                            <td class="text-right">
                                <a href="{{ route($moduleBasicRoute . '.edit', $result->id) }}" class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i> {{ trans('admin.edit') }}</a>
                                <button class="btn btn-danger btn-xs" data-toggle="modal" data-target="#deleteModal{{ $result->id }}"><i class="fa fa-remove"></i> {{ trans('admin.delete') }}</button>
                            </td>
                        </tr>
                        @endforeach

                    </tbody>
                    
                </table>
                
                <hr>
                <div class="row">
                    <div class="col-xs-12 text-center"> 
                        {!! $results->render() !!}
                    </div>
                </div>
            </div>
            <!-- Data table -->
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>
@endsection

@section('foot')
@include('admin/modules/delete_modals');
@parent
@endsection